name: ci-docker-build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      
      - name: Build image (Dockerfile in app/)
        run: docker build -f app/Dockerfile app -t team-python-env:ci

