name: ci-docker-build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show tree (debug)
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -iname "Dockerfile" -print

      - uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build \
            -f Dockerfile \
            -t team-python-env:ci \
            .