name: ci-docker-build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile \
            -t team-python-env:ci \
            .
